# This Makefile builds 2 permutations of autodock 4.2 for POWER7 for doing just 1 docking at a time:
# autodock-power7-omp-nompi --- This is the POWER7 OpenMP-only parallelization version for doing just 1 docking.
# autodock-power7-serial-nompi --- This is the POWER7 serial version for doing just 1 docking.
# This Makefile is designed to build just 1 version at a time since the same object file names are used for all targets

autodock-power7-omp-nompi: cleanpower7 autodock4-power7-omp-nompi

autodock-power7-serial-nompi: cleanpower7 autodock4-power7-serial-nompi

cleanpower7:
	touch dummy.o
	rm *.o
	touch autodock4-power7-omp-nompi
	rm -rf autodock4-power7-omp-nompi
	touch autodock4-power7-serial-nompi
	rm -rf autodock4-power7-serial-nompi

autodock4-power7-omp-nompi:	
	export OBJECT_MODE=64;make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPOWER7=1 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/vol/compilers/5.3/vac11.1.0.1/usr/vacpp/bin/xlc_r' SELECTED_CPPCOMPILER='/vol/compilers/5.3/vac11.1.0.1/usr/vacpp/bin/xlC_r' AR='/usr/bin/ar' AM_CXXFLAGS='-O3 -qsmp=omp -q64' AUTODOCK_EXEC_NAME=autodock4-power7-omp-nompi EXPORTOBJMODE='export OBJECT_MODE=64' autodock4-power7-omp-nompi
	mv autodock4-power7-omp-nompi autodock-power7-omp-nompi

autodock4-power7-serial-nompi:	
	export OBJECT_MODE=64;make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPOWER7=1 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/vol/compilers/AIX/xlc11.1.0.4/usr/vacpp/bin/xlc_r' SELECTED_CPPCOMPILER='/vol/compilers/AIX/xlc11.1.0.4/usr/vacpp/bin/xlC_r' AR='/usr/bin/ar' AM_CXXFLAGS='-O3 -q64' AUTODOCK_EXEC_NAME=autodock4-power7-serial-nompi EXPORTOBJMODE='export OBJECT_MODE=64' autodock4-power7-serial-nompi
	mv autodock4-power7-serial-nompi autodock-power7-serial-nompi
