# This Makefile builds the 3 permutations of autodock 4.2 for BlueGene/P:
# autodock-bgp-omp-mpi --- This is the BGP hybrid-parallelization version using MPI and OpenMP.
# autodock-bgp-omp-nompi --- This is the BGP OpenMP-only parallelization version for doing just 1 docking.
# autodock-power7-omp-nompi --- This is the POWER7 OpenMP-only parallelization version for doing just 1 docking.
# This Makefile is designed to build just 1 version at a time since the same object file names are used for all targets

autodock-bgp-omp-mpi: cleanbgpmpi autodock4-bgp-omp-mpi

autodock-bgp-omp-mpi-gcc: cleanbgpmpigcc autodock4-bgp-omp-mpi-gcc

autodock-bgp-noomp-mpi-gcc: cleanbgpmpigcc autodock4-bgp-noomp-mpi-gcc

autodock-bgp-noomp-mpi: cleanbgpnoompmpi autodock4-bgp-noomp-mpi

autodock-bgp-noomp-nompi: cleanbgpnoompnompi autodock4-bgp-noomp-nompi

autodock-bgp-omp-nompi: cleanbgpnompi autodock4-bgp-omp-nompi

cleanbgpmpi:
	touch dummy.o
	rm *.o
	touch autodock4-bgp-omp-mpi
	rm -rf autodock4-bgp-omp-mpi

cleanbgpmpigcc:
	touch dummy.o
	rm *.o
	touch autodock4-bgp-omp-mpi-gcc
	rm -rf autodock4-bgp-omp-mpi-gcc
	touch autodock4-bgp-noomp-mpi-gcc
	rm -rf autodock4-bgp-noomp-mpi-gcc

cleanbgpnoompmpi:
	touch dummy.o
	rm *.o
	touch autodock4-bgp-noomp-mpi
	rm -rf autodock4-bgp-noomp-mpi

cleanbgpnoompnompi:
	touch dummy.o
	rm *.o
	touch autodock4-bgp-noomp-nompi
	rm -rf autodock4-bgp-noomp-nompi

cleanbgpnompi:
	touch dummy.o
	rm *.o
	touch autodock4-bgp-omp-nompi
	rm -rf autodock4-bgp-omp-nompi

autodock4-bgp-omp-mpi:
	make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPERF_PROFILING=1 -DAUTODOCK_MPI=1 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpixlc_r' SELECTED_CPPCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpixlcxx_r' AR='/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-ar' AM_CXXFLAGS='-O3 -qsmp=omp' AUTODOCK_EXEC_NAME=autodock4-bgp-omp-mpi autodock4-bgp-omp-mpi
	mv autodock4-bgp-omp-mpi autodock-bgp-omp-mpi

autodock4-bgp-omp-mpi-gcc:
	make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPERF_PROFILING=1 -DAUTODOCK_MPI=1 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpicxx' SELECTED_CPPCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpicxx' AR='/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-ar' AM_CXXFLAGS='-O3 -fopenmp' AUTODOCK_EXEC_NAME=autodock4-bgp-omp-mpi-gcc CXX='/bgsys/drivers/ppcfloor/comm/bin/mpicxx' autodock4-bgp-omp-mpi-gcc
	mv autodock4-bgp-omp-mpi-gcc autodock-bgp-omp-mpi-gcc

autodock4-bgp-noomp-mpi-gcc:
	make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPERF_PROFILING=1 -DAUTODOCK_MPI=1 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpicxx' SELECTED_CPPCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpicxx' AR='/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-ar' AM_CXXFLAGS='-O3 ' AUTODOCK_EXEC_NAME=autodock4-bgp-noomp-mpi-gcc CXX='/bgsys/drivers/ppcfloor/comm/bin/mpicxx' autodock4-bgp-noomp-mpi-gcc
	mv autodock4-bgp-noomp-mpi-gcc autodock-bgp-noomp-mpi-gcc

autodock4-bgp-noomp-mpi:
	make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPERF_PROFILING=1 -DAUTODOCK_MPI=1 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpixlc_r' SELECTED_CPPCOMPILER='/bgsys/drivers/ppcfloor/comm/bin/mpixlcxx_r' AR='/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-ar' AM_CXXFLAGS='-O3' AUTODOCK_EXEC_NAME=autodock4-bgp-noomp-mpi autodock4-bgp-noomp-mpi
	mv autodock4-bgp-noomp-mpi autodock-bgp-noomp-mpi

autodock4-bgp-omp-nompi:
	make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/opt/ibmcmp/vacpp/bg/9.0/bin/bgxlc_r' SELECTED_CPPCOMPILER='/opt/ibmcmp/vacpp/bg/9.0/bin/bgxlC_r' AR='/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-ar'  AM_CXXFLAGS='-O3 -qsmp=omp' AUTODOCK_EXEC_NAME=autodock4-bgp-omp-nompi autodock4-bgp-omp-nompi
	mv autodock4-bgp-omp-nompi autodock-bgp-omp-nompi

autodock4-bgp-noomp-nompi:
	make -f Makefile.base DEFS='-DMAX_NUM_THREADS=16 -DPACKAGE_NAME=\"autodock\" -DPACKAGE_TARNAME=\"autodock\" -DPACKAGE_VERSION=\"4.2.2.1\" -DPACKAGE_STRING=\"autodock\ 4.2.2.1\" -DPACKAGE_BUGREPORT=\"autodock@scripps.edu\" -DPACKAGE=\"autodock\" -DVERSION=\"4.2.2.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_GETHOSTNAME=1 -DHAVE_POW=1 -DHAVE_SQRT=1 -DHAVE_STRNCASECMP=1' SELECTED_CCOMPILER='/opt/ibmcmp/vacpp/bg/9.0/bin/bgxlc_r' SELECTED_CPPCOMPILER='/opt/ibmcmp/vacpp/bg/9.0/bin/bgxlC_r' AR='/bgsys/drivers/ppcfloor/gnu-linux/bin/powerpc-bgp-linux-ar'  AM_CXXFLAGS='-O3' AUTODOCK_EXEC_NAME=autodock4-bgp-noomp-nompi autodock4-bgp-noomp-nompi
	mv autodock4-bgp-noomp-nompi autodock-bgp-noomp-nompi
